apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: istio.codefeeling.com.br # <-- Add Your HostName here
  dnsNames:
  -  istio.codefeeling.com.br # <-- Add Your HostName here
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io